"""Plots the results generated by lab.py as a coloured bar chart"""
import os
import numpy as np
import matplotlib.pyplot as plt

if __name__ == '__main__':
    # Construct path to output directory
    this_dir = os.path.dirname(os.path.abspath(__file__))
    output_dir = os.path.join(this_dir, os.pardir, "output")

    # Load output of lab.py
    args = np.load(os.path.join(output_dir, 'state.npy'))
    colours = np.load(os.path.join(output_dir, 'colours.npy')).astype(np.float64)
    colours /= 255.0 # matplotlib expects colours in [0,1], not [0, 255]

    # Plot coloured bar chart
    plt.bar(range(len(args)), args, color=colours)
    plt.show()